export const GET_RELATIONS = 'GET_RELATIONS';
export const GET_FRIENDS = 'GET_FRIENDS';
export const GET_USERS = 'GET_USERS';
export const SEND_REQUEST = 'SEND_REQUEST';
export const ACCEPT_REQUEST = 'ACCEPT_REQUEST';
export const DECLINE_UNFRIEND = 'DECLINE_UNFRIEND';
export const SEARCH_USERS = 'SEARCH_USERS';
export const RELATIONS_ERROR = 'RELATIONS_ERROR';